# Generated by Django 4.2 on 2024-07-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='named_url',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='url',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
